[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
license = "GPL-3.0-or-later"
repository = "https://github.com/julas23/orbit_panel"
authors = ["Juliano <julianoas@gmail.com>"]

[workspace.dependencies]
orbit-core = { path = "crates/orbit-core" }
orbit-backend-x11 = { path = "crates/orbit-backend-x11" }
orbit-backend-wayland = { path = "crates/orbit-backend-wayland" }

gtk = { package = "gtk4", version = "0.11", features = ["v4_12"] }
gdk4-x11 = "0.11"
gdk4-wayland = "0.11"
gtk4-layer-shell = "0.8"
x11rb = "0.14"
gio-unix = "0.22"
serde = { version = "1", features = ["derive"] }
serde_yaml_ng = "0.10"
anyhow = "1"
log = "0.4"
env_logger = "0.11"
