[package]
name = "orbit-core"
description = "Shared configuration, styling and backend abstraction for Orbit Panel"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
gtk.workspace = true
serde.workspace = true
serde_yaml_ng.workspace = true
anyhow.workspace = true
log.workspace = true
